language: objective-c
osx_image: xcode8.0
xcode_project: FastXML.xcodeproj
xcode_sdk: iphonesimulator9.3
branches:
  only:
    - master
env:
  global:
  - FRAMEWORK_NAME=FastXML
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - rvm get head || true
script:
  - set -e
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
