language: objective-c
osx_image: xcode8.0
xcode_project: FastXML.xcodeproj
xcode_sdk: iphonesimulator9.3
branches:
  only:
    - master
env:
  global:
  - FRAMEWORK_NAME=FastXML
before_install:
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    rvm get stable
  fi
#  - brew update
#  - brew outdated carthage || brew upgrade carthage
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
